/*유저 액션 타입*/

export const USER_ACTION_TYPE = {
    USER_LOADING: "USER_LOADING",
    /*로그인*/
    USER_LOG_IN_REQUEST: "USER_LOG_IN_REQUEST",
    USER_LOG_IN_SUCCESS: "USER_LOG_IN_SUCCESS",
    USER_LOG_IN_FAILURE: "USER_LOG_IN_FAILURE",
    /*로그 아웃*/
    USER_LOG_OUT_REQUEST: "USER_LOG_OUT_REQUEST",
    USER_LOG_OUT_SUCCESS: "USER_LOG_OUT_SUCCESS",
    USER_LOG_OUT_FAILURE: "USER_LOG_OUT_FAILURE",
    /*유저 정보*/
    USER_INFO_REQUEST: "USER_LOG_IN",
    USER_INFO_SUCCESS: "USER_LOG_IN",
    USER_INFO_FAILURE: "USER_LOG_IN"
}
